ToDo/Pages/AddWork.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDo.Data;
using ToDo.Data.Models;

namespace ToDo.Pages
{
    public class AddWorkModel : PageModel
    {
		[BindProperty] public string Name { get; set; }
		[BindProperty] public string Description { get; set; }

		private WorkDbContext _context;
		public AddWorkModel(WorkDbContext context)
		{
			_context = context;
		}
		public void OnGet()
        {
        }
		public IActionResult OnPost() 
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}
			var work = new Work()
			{
				Name = Name,
				Description = Description,
				TimeCreated = DateTime.Now,
				TimeLastUpdated = DateTime.Now
			};
			_context.Works.Add(work);
			_context.SaveChanges();
			return Redirect("Works");
		}
    }
}

ToDo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ToDo.Pages
{
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

ToDo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDo.Pages
{
	public class IndexModel : PageModel
	{
		private readonly ILogger<IndexModel> _logger;

		public IndexModel(ILogger<IndexModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{

		}
	}
}

ToDo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDo.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

ToDo/Pages/Works.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDo.Data;
using ToDo.Data.Models;

namespace ToDo.Pages
{
    public class WorksModel : PageModel
    {
        public List<Work> Works { get; set; }
        
        private WorkDbContext _context;
        public WorksModel(WorkDbContext context)
        {
            _context = context;
        }
        public void OnGet()
        {
            Works = _context.Works.OrderByDescending(x => x.TimeCreated).ToList();
        }
        public IActionResult OnPostClickFinished(int id)
        {
            Work? _data = _context.Works.FirstOrDefault<Work>(n => n.Id == id);
            if (_data != null)
            {
                _data.TimeLastUpdated = DateTime.Now;
                _data.Finished = true;
                _context.Update(_data);
                _context.SaveChanges();
            }
            Works = _context.Works.OrderByDescending(x => x.TimeCreated).ToList();
            return Page();
		}
    }
}

ToDo/Pages/AddWork.cshtml
@page
@model ToDo.Pages.AddWorkModel
@{
	ViewData["Title"] = "Add new work";
}

<h3>@ViewData["Title"]</h3>
<hr />

<div class="row">
	<div class="col-md-6 offset-3">
		<form method="post">
			<div class="mb-3">
				<label for="title" class="form-label">Title*</label>
				<input name="Name" type="text" class="form-control" id="title" placeholder="Job title" />
				<span asp-validation-for="@Model.Name" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label for="description" class="form-label">Description*</label>
				<textarea name="Description" class="form-control" id="description" rows="3"></textarea>
			</div>

			<button type="submit" class="btn btn-success">Add Work</button>
		</form>
	</div>
</div>

ToDo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center mt-5 pt-5">
    <h1 class="display-4">To - Do</h1>
</div>
<div class="text-center mt-5">
    <h4>A simple app to maintain your own <b>To - Do list</b>.</h4>
    <h4>Be organized !</h4>
</div>
<div class="text-center mt-5">
    <a href="/Works"><button class="btn btn-success">Let's Go</button></a>
</div>

ToDo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Works">Work</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDo - Harsh Kumar
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDo/Pages/Works.cshtml
@page
@model ToDo.Pages.WorksModel
@{
	ViewData["Title"] = "Work To-Do";
}

<h3>@ViewData["Title"]</h3>
<hr />

<table class="table table-striped">
	<thead>
		<tr>
			<th scope="col">Job</th>
			<th scope="col">Description</th>
			<th scope="col">Time Created</th>
			<th scope="col">Last Modified</th>
			<th scope="col">Action</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var _work in Model.Works)
		{
			<tr>
				<td>@_work.Name</td>
				<td>@_work.Description</td>
				<td>@_work.TimeCreated</td>
				<td>@_work.TimeLastUpdated</td>
				@if (_work.Finished)
				{
					<td>FINISHED</td>
				}
				else 
				{
					<td>
						<form asp-page-handler="ClickFinished" method="post">
							<input type="hidden" name="id" value="@_work.Id" />
							<button class="btn btn-success">Finish</button>
						</form>
					</td>
				}
			</tr>
		}
	</tbody>
</table>

<div style="position: fixed; bottom: 70px;right:25px;">
	<a href="/AddWork" class="btn btn-success">Add New</a>
</div>